language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1
cache:
  - bundler
branches:
  only:
    - master
    - /^greenkeeper/.*$/
script:
  - bundle exec rake travis:script
after_success:
  - bundle exec rake travis:after_success
